ALTER TABLE ACCOUNT ADD COLUMN IMAGE VARCHAR(100);

UPDATE ISSUE_COMMENT SET ACTION = 'comment' WHERE ACTION IS NULL;

ALTER TABLE ISSUE_COMMENT ALTER COLUMN ACTION VARCHAR(20) NOT NULL;

UPDATE ISSUE_COMMENT SET ACTION = 'close_comment'  WHERE ACTION = 'close';
UPDATE ISSUE_COMMENT SET ACTION = 'reopen_comment' WHERE ACTION = 'reopen';
