ALTER TABLE ACCOUNT ADD COLUMN IMAGE VARCHAR(100);

ALTER TABLE REPOSITORY ADD COLUMN ORIGIN_USER_NAME VARCHAR(100);
ALTER TABLE REPOSITORY ADD COLUMN ORIGIN_REPOSITORY_NAME VARCHAR(100);

CREATE TABLE PULL_REQUEST(
		PULL_REQUEST_ID INT AUTO_INCREMENT,
		USER_NAME VARCHAR(100) NOT NULL,
		REPOSITORY_NAME VARCHAR(100) NOT NULL,
		ISSUE_ID INT NOT NULL,
		COMMIT_ID VARCHAR(40) NOT NULL
);

ALTER TABLE PULL_REQUEST ADD CONSTRAINT IDX_PULL_REQUEST_PK PRIMARY KEY (PULL_REQUEST_ID);
ALTER TABLE PULL_REQUEST ADD CONSTRAINT IDX_PULL_REQUEST_1 UNIQUE ISSUE (USER_NAME, REPOSITORY_NAME, ISSUE_ID);
