ALTER TABLE ACCOUNT ADD COLUMN IMAGE VARCHAR(100);

ALTER TABLE COMMENT ALTER COLUMN ACTION VARCHAR(20);
UPDATE COMMENT SET ACTION = 'close_comment'  WHERE ACTION = 'close';
UPDATE COMMENT SET ACTION = 'reopen_comment' WHERE ACTION = 'reopen';
