CREATE TABLE PULL_REQUEST(
		USER_NAME VARCHAR(100) NOT NULL,
		REPOSITORY_NAME VARCHAR(100) NOT NULL,
		ISSUE_ID INT NOT NULL,
		BRANCH VARCHAR(100) NOT NULL,
		REQUEST_USER_NAME VARCHAR(100) NOT NULL,
		REQUEST_REPOSITORY_NAME VARCHAR(100) NOT NULL,
		REQUEST_BRANCH VARCHAR(100) NOT NULL,
		MERGE_START_ID VARCHAR(40),
		MERGE_END_ID VARCHAR(40)
);

ALTER TABLE PULL_REQUEST ADD CONSTRAINT IDX_PULL_REQUEST_PK PRIMARY KEY (USER_NAME, REPOSITORY_NAME, ISSUE_ID);
ALTER TABLE PULL_REQUEST ADD CONSTRAINT IDX_PULL_REQUEST_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME, ISSUE_ID) REFERENCES ISSUE (USER_NAME, REPOSITORY_NAME, ISSUE_ID);
ALTER TABLE PULL_REQUEST ADD CONSTRAINT IDX_PULL_REQUEST_FK1 FOREIGN KEY (REQUEST_USER_NAME, REQUEST_REPOSITORY_NAME) REFERENCES REPOSITORY (USER_NAME, REPOSITORY_NAME);
